
FormatD:
  GeoIndexable:
    services:
      google:
        serviceClass: 'FormatD\GeoIndexable\GoogleGeoIndexableService'
        options:
          baseUri: 'https://maps.googleapis.com/maps/api/'
          apiKey: 'ichbineinapikey'
      nominatim:
        serviceClass: 'FormatD\GeoIndexable\NominatimGeoIndexableService'
        options:
          baseUri: 'http://nominatim.openstreetmap.org/'
      geonames:
        serviceClass: ''
        options:
          baseUri: 'http://api.geonames.org/'
          username: ''
